-- Create a table in the schema
BEGIN;
CREATE TABLE IF NOT EXISTS MY_SCHEMA.MY_TABLE (
    ID INT AUTOINCREMENT PRIMARY KEY,
    NAME STRING,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
COMMIT;
